const _manifest = {
  apiBaseUrl: "https://api.sharetrip.net/api/",
  hotelListSocketUrl: "https://socket.sharetrip.net/hotel",
  site: "http://sharetrip.net",
  companyName: "ShareTrip",
  companyShortName: "ST",
  contactEmail: "ask@sharetrip.net",
  contactNumber: "+8809617617617",
  companyLogo: "https://utility-assets.s3.amazonaws.com/media/assets/full-logo.png",
  companyHeadOffceAddress: "House: 45, Road: 13/C, Block: E, Banani,<br /> Dhaka, Bangladesh",
  androidAppLink: "https://tinyurl.com/y62lftzl",
  iosAppLink: "https://apple.co/2Y0DdLx",
  googleLoginClientId: "346164418203-h0aa85kn3dltnoq44lvljttpdlkcdm10.apps.googleusercontent.com",
  facebookLoginAppId: "575994546140179",
  facebookPageLink: "https://www.facebook.com/sharetripinc/",
  messengerLink: "https://www.messenger.com/t/sharetripinc",
  linkedinLink: "https://www.linkedin.com/company/sharetrip/",
  youtubeLink: "https://www.youtube.com/channel/UCWqCNCLZXgXIjRLxWrg_8gg",
  instagramLink: "https://www.instagram.com/sharetripapp/",
  twitterLink: "https://twitter.com/ShareTripLtd",
  pinterestLink: "https://www.pinterest.co.uk/sharetrip/",
  blogBaseUrl: "https://stg-blog.sharetrip.net/",
};
export default _manifest;
